name: wcap

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Build
        shell: cmd
        run: cd repo && build.cmd

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: wcap
          path: repo/wcap.exe
